// SPDX-FileCopyrightText: 2026 Ergentics, LLC
// SPDX-License-Identifier: LicenseRef-Ergentics-Proprietary

import Dispatch
import Foundation
import Metal
import MLX
import PrimeCore
import PrimeNativeDecoder
import PrimeNativeDecoderCheckpoint

/// Inference from supplied, verified checkpoint bytes. This API neither
/// trains the model nor supplies a chat template, response text, or token mask.
public enum PrimeNativeDecoderCurrentLocalGeneration {
    public static let maximumPromptByteTokens = 1_023
    public static let maximumGeneratedTokens = 256
    public static let maximumDurationNanoseconds: UInt64 = 300_000_000_000

    public enum Failure: Error, Equatable, LocalizedError {
        case rejected(String)
        public var errorDescription: String? {
            switch self { case .rejected(let reason): return "Prime generation rejected: \(reason)" }
        }
    }

    public enum StopReason: String, Codable, Sendable {
        case endOfSequence, tokenLimit
    }

    public struct TokenEvent: Codable, Equatable, Sendable {
        public let ordinal: Int
        public let tokenID: Int
        /// Actual final-position logits, in all 512 vocabulary positions.
        public let logitFloat32Bits: [UInt32]
        public let logitFloat32LittleEndianSHA256: String
        public let cachePosition: Int
    }

    public struct Output: Codable, Equatable, Sendable {
        public let renderedOutput: String
        /// Exact UTF-8 text only when all nonterminal tokens are byte tokens.
        /// This does not normalize or repair the model's generated bytes.
        public let decodedText: String?
    }

    public struct Result: Codable, Sendable {
        public let schema: String
        public let question: String
        public let canonicalQuestion: String
        public let promptTokenIDs: [Int]
        public let promptTokenIDsSHA256: String
        public let prefillNextTokenLogitsSHA256: String
        public let generatedTokenIDs: [Int]
        public let renderedOutput: String
        public let decodedText: String?
        public let stopReason: StopReason
        public let decoding: String
        public let events: [TokenEvent]
        public let checkpointCommitSHA256: String
        public let weightsBinding: PrimeArtifactBinding
        public let modelParameterCount: Int64
        public let startedAt: UInt64
        public let completedAt: UInt64
    }

    public static func generate(
        artifactRoot: PrimeArtifactRoot,
        checkpoint: PrimeNativeDecoderNative300MTrajectoryExternalCommitBindingV1,
        question: String,
        maximumNewTokens: Int,
        deadlineNanoseconds: UInt64,
        lease: PrimeMetalDeviceLease,
        recordToken: (TokenEvent) throws -> Void
    ) throws -> Result {
        let startedAt = DispatchTime.now().uptimeNanoseconds
        let prompt = try preparePrompt(question, maximumNewTokens: maximumNewTokens)
        guard deadlineNanoseconds > startedAt,
              deadlineNanoseconds - startedAt <= maximumDurationNanoseconds else {
            throw Failure.rejected("deadline must be within 300 seconds")
        }
        func checkpointTime() throws {
            guard lease.isHeld else { throw Failure.rejected("device lease is no longer held") }
            let now = DispatchTime.now().uptimeNanoseconds
            guard now >= startedAt, now < deadlineNanoseconds else {
                throw Failure.rejected("generation deadline expired")
            }
        }
        try checkpointTime()
        let devices = MTLCopyAllDevices()
        guard devices.count == 1, let metal = devices.first,
              let selected = MTLCreateSystemDefaultDevice(),
              selected.registryID == metal.registryID, metal.hasUnifiedMemory,
              ProcessInfo.processInfo.environment["MLX_ENABLE_TF32"] == "0" else {
            throw Failure.rejected("requires the admitted default unified Metal device and TF32 disabled")
        }
        let memoryLimit = min(UInt64(17_179_869_184), UInt64(metal.recommendedMaxWorkingSetSize))
        guard memoryLimit >= 4_337_713_152, memoryLimit <= UInt64(Int.max) else {
            throw Failure.rejected("insufficient native model memory limit")
        }
        return try Device.withDefaultDevice(Device(.gpu, index: 0)) {
            MLX.Memory.memoryLimit = Int(memoryLimit)
            MLX.Memory.cacheLimit = 0
            try PrimeNativeDecoderNative300MTrajectoryCheckpointV1.validateExternalBinding(checkpoint)
            guard checkpoint.setRole == .baselineCheckpoint, checkpoint.loadAuthoritative else {
                throw Failure.rejected("generation requires the retained authoritative baseline")
            }
            // Inference imports only the verified weight container. The
            // retained optimizer/control leaves are neither loaded nor changed.
            let model = try PrimeNativeDecoderCheckpointCodecV2.loadNative300MByte512(
                expected: checkpoint.weightsExternalBinding, from: artifactRoot)
            try checkpointTime()
            guard model.configuration == (try .native300MInventory(vocabularySize: 512)),
                  model.configuration.uniqueParameterCount == 271_107_072 else {
                throw Failure.rejected("checkpoint is not Native-300M byte512")
            }
            model.train(false)
            let cache = try model.makeCache(batchSize: 1)
            defer { cache.reset(); MLX.Memory.clearCache() }
            let decoded = try decode(promptTokenIDs: prompt.tokenIDs, maximumNewTokens: maximumNewTokens,
                checkpoint: checkpointTime, forward: { chunk in
                    let logits = try model.forward(batchTokenIDs: [chunk], cache: cache)
                    try cache.materialize()
                    guard logits.shape == [1, chunk.count, 512], logits.dtype == .float32 else {
                        throw Failure.rejected("unexpected model logits shape or dtype")
                    }
                    let row = logits[0, chunk.count - 1, 0...]
                    return row.asArray(Float.self)
                }, recordToken: recordToken)
            try checkpointTime()
            _ = try artifactRoot.verify(checkpoint.weightsExternalBinding.artifactBinding)
            try checkpointTime()
            let output = try render(tokenIDs: decoded.tokens)
            try checkpointTime()
            return Result(schema: "prime_current_local_native300m_generation_v1",
                question: question, canonicalQuestion: prompt.canonical,
                promptTokenIDs: prompt.tokenIDs,
                promptTokenIDsSHA256: try PrimeNativeByteTokenizer.tokenIDsSHA256(prompt.tokenIDs),
                prefillNextTokenLogitsSHA256: decoded.events[0].logitFloat32LittleEndianSHA256,
                generatedTokenIDs: decoded.tokens,
                renderedOutput: output.renderedOutput, decodedText: output.decodedText,
                stopReason: decoded.stopReason, decoding: "greedy_all_512_lowest_token_id_tie",
                events: decoded.events, checkpointCommitSHA256: checkpoint.commitManifestCanonicalSHA256,
                weightsBinding: checkpoint.weightsExternalBinding.artifactBinding,
                modelParameterCount: model.configuration.uniqueParameterCount,
                startedAt: startedAt, completedAt: DispatchTime.now().uptimeNanoseconds)
        }
    }

    static func preparePrompt(_ question: String, maximumNewTokens: Int) throws -> (canonical: String, tokenIDs: [Int]) {
        guard !question.isEmpty, question.utf8.count <= 4_096,
              (1...maximumGeneratedTokens).contains(maximumNewTokens) else {
            throw Failure.rejected("empty/oversized question or output limit outside 1...256")
        }
        let canonical = PrimeNativeByteTokenizer.canonicalize(question)
        let bytes = PrimeNativeByteTokenizer.encode(question)
        guard !bytes.isEmpty, bytes.count <= maximumPromptByteTokens else {
            throw Failure.rejected("canonical question exceeds 1023 UTF-8 byte tokens")
        }
        // EOS is not appended: the next prediction continues the actual prompt.
        return (canonical, [PrimeNativeByteTokenizer.beginningOfSequenceTokenID] + bytes)
    }

    struct Decoded {
        let tokens: [Int]
        let events: [TokenEvent]
        let stopReason: StopReason
    }

    /// Shared scheduling/selection mechanics; the public entry supplies only
    /// the actual loaded model's cached forward. Tests can exercise this loop
    /// without constructing Native-300M or pretending to run its workload.
    static func decode(
        promptTokenIDs: [Int], maximumNewTokens: Int,
        checkpoint: () throws -> Void,
        forward: ([Int]) throws -> [Float],
        recordToken: (TokenEvent) throws -> Void
    ) throws -> Decoded {
        guard !promptTokenIDs.isEmpty, promptTokenIDs.count <= maximumPromptByteTokens + 1,
              promptTokenIDs.first == PrimeNativeByteTokenizer.beginningOfSequenceTokenID,
              promptTokenIDs.dropFirst().allSatisfy(PrimeNativeByteTokenizer.byteTokenRange.contains),
              (1...maximumGeneratedTokens).contains(maximumNewTokens) else {
            throw Failure.rejected("invalid tokenized prompt or output bound")
        }
        var chunk = promptTokenIDs
        var position = 0
        var tokens: [Int] = []
        var events: [TokenEvent] = []
        for ordinal in 0..<maximumNewTokens {
            try checkpoint()
            let row = try forward(chunk)
            try checkpoint()
            position += chunk.count
            let token = try greedyToken(row)
            let bits = row.map(\.bitPattern)
            var bytes = Data()
            bytes.reserveCapacity(512 * MemoryLayout<UInt32>.size)
            for value in bits {
                var littleEndian = value.littleEndian
                withUnsafeBytes(of: &littleEndian) { bytes.append(contentsOf: $0) }
            }
            let event = TokenEvent(ordinal: ordinal, tokenID: token,
                logitFloat32Bits: bits,
                logitFloat32LittleEndianSHA256: PrimeSHA256.hexDigest(of: bytes),
                cachePosition: position)
            try recordToken(event)
            try checkpoint()
            tokens.append(token)
            events.append(event)
            if token == PrimeNativeByteTokenizer.endOfSequenceTokenID {
                return Decoded(tokens: tokens, events: events, stopReason: .endOfSequence)
            }
            chunk = [token]
        }
        return Decoded(tokens: tokens, events: events, stopReason: .tokenLimit)
    }

    static func greedyToken(_ logits: [Float]) throws -> Int {
        guard logits.count == 512, logits.allSatisfy(\.isFinite) else {
            throw Failure.rejected("model logits must contain exactly 512 finite Float32 values")
        }
        var selected = 0
        for index in 1..<logits.count where logits[index] > logits[selected] { selected = index }
        return selected
    }

    /// Raw token IDs remain authoritative. Rendering never substitutes a
    /// response for symbolic predictions or silently repairs invalid UTF-8.
    public static func render(tokenIDs: [Int]) throws -> Output {
        guard tokenIDs.count <= maximumGeneratedTokens,
              tokenIDs.allSatisfy({ (0..<512).contains($0) }) else {
            throw Failure.rejected("invalid output token sequence")
        }
        var rendered = ""
        var run: [UInt8] = []
        var allBytes: [UInt8] = []
        var onlyBytesAndTerminalEOS = true
        func flush() {
            guard !run.isEmpty else { return }
            if let text = String(bytes: run, encoding: .utf8) {
                rendered += text
            } else {
                rendered += "⟦bytes:" + run.map { String(format: "%02x", $0) }.joined() + "⟧"
            }
            run.removeAll(keepingCapacity: true)
        }
        for (index, token) in tokenIDs.enumerated() {
            if PrimeNativeByteTokenizer.byteTokenRange.contains(token) {
                let byte = try PrimeNativeByteTokenizer.byte(forTokenID: token)
                run.append(byte); allBytes.append(byte)
            } else {
                flush()
                rendered += "⟦token:\(token)⟧"
                if token != PrimeNativeByteTokenizer.endOfSequenceTokenID || index != tokenIDs.count - 1 {
                    onlyBytesAndTerminalEOS = false
                }
            }
        }
        flush()
        return Output(renderedOutput: rendered,
            decodedText: onlyBytesAndTerminalEOS ? String(bytes: allBytes, encoding: .utf8) : nil)
    }
}
