import CryptoKit
import Foundation
import GateEStaticBootstrapPrimitives

// SOURCE-ONLY implementation of control 568d22b. No build/launch authority is
// conveyed by these declarations. All native process entry is private to Run.
// Existing worker outputs are read, never regenerated by this module.
enum BootstrapFailure: Error { case reject(String) }
@inline(__always)
func require(_ condition: Bool, _ reason: String) throws {
    guard condition else { throw BootstrapFailure.reject(reason) }
}
func bootstrapSHA256(_ bytes: [UInt8]) -> String {
    SHA256.hash(data: Data(bytes)).map { String(format: "%02x", $0) }.joined()
}

enum Stage: Int, CaseIterable, Sendable {
    case json, cbor, join
    var label: String { ["JSON", "CBOR", "JOIN"][rawValue] }
    var entryLeaf: String { ["10-json-enter.json", "20-cbor-enter.json", "30-join-enter.json"][rawValue] }
    var exitLeaf: String { ["15-json-exit.json", "25-cbor-exit.json", "34-join-exit.json"][rawValue] }
    var outputs: [Int32: String] {
        switch self {
        case .json: [1: "11-json-verifier.json", 2: "14-json-stderr.bin", 3: "12-json-graph.json", 4: "13-json-roundtrip.json"]
        case .cbor: [1: "21-cbor-verifier.json", 2: "24-cbor-stderr.bin", 3: "22-cbor-graph.json", 4: "23-cbor-roundtrip.json"]
        case .join: [1: "31-join-receipt.json", 2: "33-join-stderr.bin", 8: "32-authoritative-static-graph.json"]
        }
    }
    var inputs: [Int32: String] {
        switch self {
        case .json: [0: "candidate-json.bin"]
        case .cbor: [0: "candidate-cbor.bin"]
        case .join: [0: "12-json-graph.json", 3: "11-json-verifier.json", 4: "13-json-roundtrip.json",
                     5: "22-cbor-graph.json", 6: "21-cbor-verifier.json", 7: "23-cbor-roundtrip.json"]
        }
    }
}
enum Codec: String, Sendable {
    case json = "JSON", cbor = "CBOR"
    var candidateHash: String {
        switch self {
        case .json: "cda57fec7b6ee67d308eddc1f19d6a844d7f72f7d02aea487ee73e265039961e"
        case .cbor: "c7242f65b69d16f05c67425241297e4e5d598eecc4155aca01c73e40af817636"
        }
    }
}
final class OneShotLatch: @unchecked Sendable {
    private let lock = NSLock()
    private var consumed = false
    func consume() throws {
        lock.lock()
        defer { lock.unlock() }
        try require(!consumed, "one-shot already consumed")
        consumed = true
    }
}
enum BoundaryChecks {
    // Necessary completeness predicate only. It cannot construct the private
    // live admission token, which independently reads every held descriptor.
    static func requireComplete(sourceMetadata: Int, sourceDigests: Int,
                                imageMetadata: Int, imageDigests: Int, endpoints: Bool) throws {
        try require(sourceMetadata == 13 && sourceDigests == 13 &&
                    imageMetadata == 3 && imageDigests == 3 && endpoints, "incomplete boundary")
    }
}
struct Vnode: Hashable, Sendable { let device: UInt64; let inode: UInt64 }
enum EndpointChecks {
    static func input(offset: Int64, readOnly: Bool, sourceFD: Int32, targetFD: Int32) throws {
        try require(offset == 0 && readOnly && sourceFD >= 32 && targetFD >= 0 && targetFD <= 8,
                    "input cursor/access/parking")
    }
    static func disjoint(inputs: [Vnode], outputs: [Vnode]) throws {
        try require(Set(outputs).count == outputs.count && Set(inputs).isDisjoint(with: outputs),
                    "endpoint vnode alias")
    }
    static func plan(stage: Stage, inputs: [Int32: Int32], outputs: [Int32: Int32]) throws {
        try require(Set(inputs.keys) == Set(stage.inputs.keys) &&
                    Set(outputs.keys) == Set(stage.outputs.keys), "FD target map")
        let all = Array(inputs.values) + Array(outputs.values)
        try require(all.allSatisfy { $0 >= 32 } && Set(all).count == all.count, "FD source collision")
    }
}
enum WaitObservation { case running, interrupted, reaped(Int32), lost(Int32) }
struct ChildOwnership {
    let pid: Int32
    private(set) var isReaped = false
    private(set) var ownershipLost = false
    private(set) var killCommitted = false
    private(set) var rawWaitStatus: Int32?
    init(pid: Int32) throws {
        try require(pid > 0, "positive owned PID")
        self.pid = pid
    }
    mutating func observe(_ observation: WaitObservation) throws {
        try require(!isReaped && !ownershipLost, "terminal ownership")
        switch observation {
        case .running, .interrupted: break
        case .reaped(let status): isReaped = true; rawWaitStatus = status
        case .lost: ownershipLost = true
        }
    }
    mutating func commitKill() throws -> Int32 {
        try require(!isReaped && !ownershipLost && !killCommitted, "KILL ownership/one-shot")
        killCommitted = true
        return pid
    }
}
enum Deadline {
    static func expired(start: UInt64, now: UInt64, numerator: UInt32, denominator: UInt32) throws -> Bool {
        try require(now >= start && numerator > 0 && denominator > 0, "clock/timebase")
        // Exact unsigned 128-bit products as two limbs: Swift.UInt128 itself
        // requires macOS15, while this frozen package retains its macOS14 floor.
        let left = (now - start).multipliedFullWidth(by: UInt64(numerator))
        let right = UInt64(5_000_000_000).multipliedFullWidth(by: UInt64(denominator))
        return left.high > right.high || (left.high == right.high && left.low >= right.low)
    }
}
struct StageSequencer {
    private var index = 0
    private var poisoned = false
    var next: Stage? { poisoned ? nil : Stage(rawValue: index) }
    mutating func finish(_ stage: Stage) throws {
        guard next == stage else { poisoned = true; throw BootstrapFailure.reject("stage order") }
        index += 1
    }
    mutating func reject() { poisoned = true }
}

struct GraphBinding: Equatable, Sendable { let frameHash: String; let merkleRoot: String }
enum ReceiptBinding {
    // Exact closed flat grammars. No general JSON parser, substring scraping,
    // or worker receipt generation; every input byte is consumed once.
    private enum Field { case literal(String), hex }
    private static func parse(_ bytes: [UInt8], _ fields: [(String, Field)]) throws -> [String: String] {
        try require(!bytes.isEmpty && bytes.count <= 262_144, "receipt cap")
        var cursor = 0
        func take(_ literal: String) throws {
            let expected = Array(literal.utf8)
            try require(cursor <= bytes.count && expected.count <= bytes.count - cursor &&
                        bytes[cursor..<(cursor + expected.count)].elementsEqual(expected), "receipt grammar")
            cursor += expected.count
        }
        var hashes: [String: String] = [:]
        try take("{")
        for (index, field) in fields.enumerated() {
            if index > 0 { try take(",") }
            try take("\"\(field.0)\":\"")
            switch field.1 {
            case .literal(let value): try take(value)
            case .hex:
                try require(cursor <= bytes.count && 64 <= bytes.count - cursor, "receipt hash length")
                let value = Array(bytes[cursor..<(cursor + 64)])
                try require(value.allSatisfy { (48...57).contains($0) || (97...102).contains($0) }, "receipt lowerhex")
                hashes[field.0] = String(decoding: value, as: UTF8.self)
                cursor += 64
            }
            try take("\"")
        }
        try take("}")
        try require(cursor == bytes.count, "receipt trailing bytes")
        return hashes
    }
    static func projector(codec: Codec, graph: [UInt8], verifier: [UInt8], roundTrip: [UInt8]) throws -> GraphBinding {
        try require(!graph.isEmpty && graph.count <= 16_777_216, "graph cap")
        let digest = bootstrapSHA256(graph)
        let v = try parse(verifier, [
            ("candidate_sha256", .hex), ("graph_frame_sha256", .hex), ("graph_merkle_root", .hex),
            ("result", .literal("PASS")), ("schema", .literal("ergentics.gate-e.static.verifier-receipt.v1")),
            ("semantic_root", .hex), ("source_authority", .literal(codec.rawValue)),
        ])
        let r = try parse(roundTrip, [
            ("candidate_sha256", .hex), ("graph_frame_sha256", .hex), ("graph_merkle_root", .hex),
            ("original_semantic_root", .hex), ("reconstructed_candidate_sha256", .hex),
            ("reconstructed_graph_frame_sha256", .hex), ("reconstructed_semantic_root", .hex),
            ("result", .literal("PASS")), ("schema", .literal("ergentics.gate-e.static.round-trip-receipt.v1")),
            ("source_authority", .literal(codec.rawValue)),
        ])
        try require(v["candidate_sha256"] == codec.candidateHash &&
                    r["candidate_sha256"] == codec.candidateHash &&
                    r["reconstructed_candidate_sha256"] == codec.candidateHash, "external candidate join")
        try require(v["graph_frame_sha256"] == digest && r["graph_frame_sha256"] == digest &&
                    r["reconstructed_graph_frame_sha256"] == digest, "actual graph join")
        try require(v["semantic_root"] == StaticPins.semanticRoot &&
                    r["original_semantic_root"] == StaticPins.semanticRoot &&
                    r["reconstructed_semantic_root"] == StaticPins.semanticRoot, "external semantic join")
        guard let merkle = v["graph_merkle_root"], r["graph_merkle_root"] == merkle else {
            throw BootstrapFailure.reject("projector Merkle join")
        }
        return GraphBinding(frameHash: digest, merkleRoot: merkle)
    }
    static func join(graph: [UInt8], jsonGraph: [UInt8], cborGraph: [UInt8], receipt: [UInt8],
                     json: GraphBinding, cbor: GraphBinding) throws {
        try require(!graph.isEmpty && graph.count <= 16_777_216 &&
                    graph == jsonGraph && graph == cborGraph && json == cbor, "dual graph bytes")
        let r = try parse(receipt, [
            ("authority_vector", .literal("00000000")), ("cbor_graph_frame_sha256", .hex),
            ("graph_merkle_root", .hex), ("json_graph_frame_sha256", .hex),
            ("projection_write_mask", .literal("00000000")), ("result", .literal("PASS")),
            ("schema", .literal("ergentics.gate-e.static.dual-graph-join-receipt.v1")), ("semantic_root", .hex),
        ])
        let digest = bootstrapSHA256(graph)
        try require(json.frameHash == digest && r["cbor_graph_frame_sha256"] == digest &&
                    r["json_graph_frame_sha256"] == digest && r["graph_merkle_root"] == json.merkleRoot &&
                    r["semantic_root"] == StaticPins.semanticRoot, "independent join receipt")
    }
}

private struct FilePin: Sendable {
    let path: String
    let size: Int
    let digest: String
    let mode: UInt32
    let device: UInt64?
    let inode: UInt64?
    let image: String?
}

enum StaticPins {
    static let controlCommit = "568d22bf35c37ffc165580631bfd0da97701d61f"
    static let controlDigest = "35a9a5c01d98bf42dbbfc394f1ca2c6a6b6f93194682977906d5a60f192ca2d1"
    static let semanticRoot = "093b6e90214704a3e8fdf28cf430a8c4cd106d695e621887b77db489fc5cd9bb"
    static let parentPath = "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45"
    static let runLeaf = "gate-e-static-bootstrap-c51f796-r1"
    static let sourceRoot = parentPath + "/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl"
    static let controlPath = parentPath + "/.phase-a-v2-fixture-identity-restore-only-staging/Observability/ErgenticsGateEStaticControl/Control/gate-e-static-bootstrap-admission-control.v1.json"
    // These are two independently frozen wire buffers, not one codec derived
    // from the other, not worker output, and not a live source-tree admission.
    static let jsonBytes: [UInt8] = [
        0x7b, 0x22, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x76, 0x65, 0x63, 0x74,
        0x6f, 0x72, 0x22, 0x3a, 0x22, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x22, 0x2c, 0x22,
        0x67, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x22, 0x41, 0x42, 0x53,
        0x54, 0x41, 0x49, 0x4e, 0x22, 0x2c, 0x22, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
        0x73, 0x22, 0x3a, 0x5b, 0x22, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x5f,
        0x50, 0x52, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f,
        0x34, 0x30, 0x5f, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x48, 0x45, 0x58, 0x5f, 0x4c, 0x46, 0x22, 0x2c,
        0x22, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x46, 0x4f,
        0x52, 0x4d, 0x41, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x53, 0x48, 0x41, 0x31,
        0x5f, 0x4c, 0x46, 0x22, 0x2c, 0x22, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
        0x55, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f,
        0x45, 0x58, 0x41, 0x43, 0x54, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x22, 0x2c, 0x22, 0x50, 0x52,
        0x49, 0x4d, 0x45, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45,
        0x52, 0x59, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x59,
        0x22, 0x2c, 0x22, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x5f,
        0x4d, 0x41, 0x4e, 0x49, 0x46, 0x45, 0x53, 0x54, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x53, 0x5f, 0x52,
        0x45, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x41,
        0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x22, 0x2c, 0x22, 0x43, 0x4f, 0x4d, 0x50, 0x41,
        0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x45, 0x51,
        0x55, 0x41, 0x4c, 0x53, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53,
        0x5f, 0x50, 0x49, 0x4e, 0x4e, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x22, 0x2c,
        0x22, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43,
        0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f,
        0x53, 0x48, 0x41, 0x31, 0x5f, 0x4c, 0x46, 0x22, 0x2c, 0x22, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e,
        0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x41,
        0x4e, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f, 0x45, 0x58, 0x41, 0x43, 0x54, 0x5f, 0x45, 0x4d,
        0x50, 0x54, 0x59, 0x22, 0x2c, 0x22, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f, 0x4e, 0x5f,
        0x54, 0x52, 0x45, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x45,
        0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x59, 0x22, 0x2c, 0x22, 0x43,
        0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x5f,
        0x4d, 0x41, 0x4e, 0x49, 0x46, 0x45, 0x53, 0x54, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x53, 0x5f, 0x43,
        0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x5f, 0x43,
        0x4c, 0x4f, 0x53, 0x55, 0x52, 0x45, 0x22, 0x2c, 0x22, 0x53, 0x57, 0x49, 0x46, 0x54, 0x5f, 0x56,
        0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x45, 0x44, 0x5f, 0x46,
        0x52, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4e,
        0x54, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x22, 0x2c, 0x22, 0x53, 0x57, 0x49, 0x46, 0x54, 0x5f, 0x54,
        0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x43, 0x41, 0x4e, 0x4f, 0x4e,
        0x49, 0x43, 0x41, 0x4c, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x44,
        0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x22, 0x2c, 0x22, 0x44,
        0x52, 0x49, 0x56, 0x45, 0x52, 0x43, 0x4f, 0x52, 0x45, 0x5f, 0x49, 0x4e, 0x44, 0x45, 0x50, 0x45,
        0x4e, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x50, 0x41, 0x52, 0x53, 0x45, 0x5f, 0x41, 0x4e,
        0x44, 0x5f, 0x4c, 0x49, 0x56, 0x45, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x41, 0x53, 0x53,
        0x22, 0x2c, 0x22, 0x46, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x5f, 0x49, 0x4d,
        0x41, 0x47, 0x45, 0x5f, 0x4c, 0x45, 0x41, 0x53, 0x45, 0x5f, 0x4a, 0x4f, 0x55, 0x52, 0x4e, 0x41,
        0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x41, 0x53,
        0x53, 0x22, 0x2c, 0x22, 0x46, 0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53,
        0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x45, 0x52, 0x56, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50,
        0x41, 0x53, 0x53, 0x22, 0x2c, 0x22, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x47,
        0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x45, 0x4e, 0x54, 0x52,
        0x59, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x5a, 0x45, 0x52,
        0x4f, 0x22, 0x5d, 0x2c, 0x22, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x5b, 0x22, 0x70, 0x72,
        0x69, 0x6d, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x22, 0x2c, 0x22, 0x70,
        0x72, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d,
        0x61, 0x74, 0x22, 0x2c, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
        0x73, 0x5f, 0x70, 0x72, 0x65, 0x22, 0x2c, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x72,
        0x65, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x22, 0x2c, 0x22, 0x70,
        0x72, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79,
        0x22, 0x2c, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
        0x70, 0x6f, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x68, 0x65, 0x61,
        0x64, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69,
        0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x22, 0x2c, 0x22, 0x63, 0x6f,
        0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66,
        0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x2c, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f,
        0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x22, 0x2c, 0x22, 0x63,
        0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x64, 0x69,
        0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x22, 0x2c, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
        0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x22,
        0x2c, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
        0x75, 0x73, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
        0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x22, 0x2c, 0x22,
        0x73, 0x77, 0x69, 0x66, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x22,
        0x73, 0x77, 0x69, 0x66, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66,
        0x6f, 0x22, 0x5d, 0x2c, 0x22, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x3a, 0x22, 0x65, 0x72,
        0x67, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x2d, 0x65, 0x2e, 0x73,
        0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
        0x76, 0x31, 0x22, 0x2c, 0x22, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
        0x69, 0x74, 0x22, 0x3a, 0x22, 0x30, 0x34, 0x63, 0x35, 0x33, 0x32, 0x34, 0x63, 0x63, 0x66, 0x63,
        0x36, 0x39, 0x38, 0x34, 0x61, 0x64, 0x37, 0x63, 0x34, 0x30, 0x37, 0x65, 0x39, 0x33, 0x32, 0x33,
        0x38, 0x63, 0x63, 0x34, 0x34, 0x66, 0x39, 0x63, 0x65, 0x32, 0x32, 0x64, 0x64, 0x22, 0x2c, 0x22,
        0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
        0x3a, 0x22, 0x32, 0x63, 0x32, 0x35, 0x32, 0x34, 0x36, 0x64, 0x65, 0x31, 0x62, 0x35, 0x30, 0x31,
        0x34, 0x38, 0x64, 0x38, 0x31, 0x39, 0x33, 0x31, 0x36, 0x37, 0x38, 0x38, 0x30, 0x38, 0x32, 0x38,
        0x38, 0x31, 0x35, 0x62, 0x31, 0x37, 0x63, 0x38, 0x30, 0x65, 0x38, 0x65, 0x65, 0x36, 0x36, 0x61,
        0x30, 0x39, 0x64, 0x65, 0x63, 0x34, 0x35, 0x62, 0x31, 0x34, 0x33, 0x30, 0x31, 0x37, 0x38, 0x66,
        0x63, 0x31, 0x22, 0x2c, 0x22, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x65, 0x65,
        0x22, 0x3a, 0x22, 0x31, 0x30, 0x36, 0x31, 0x35, 0x61, 0x32, 0x64, 0x36, 0x36, 0x37, 0x32, 0x30,
        0x62, 0x37, 0x30, 0x65, 0x63, 0x61, 0x66, 0x61, 0x38, 0x39, 0x31, 0x61, 0x62, 0x32, 0x36, 0x65,
        0x39, 0x36, 0x61, 0x63, 0x39, 0x65, 0x65, 0x38, 0x31, 0x32, 0x65, 0x22, 0x7d
    ]
    static let cborBytes: [UInt8] = [
        0xa8, 0x00, 0x78, 0x24, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x67, 0x61,
        0x74, 0x65, 0x2d, 0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x63, 0x61, 0x6e, 0x64,
        0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x01, 0x78, 0x28, 0x30, 0x34, 0x63, 0x35, 0x33,
        0x32, 0x34, 0x63, 0x63, 0x66, 0x63, 0x36, 0x39, 0x38, 0x34, 0x61, 0x64, 0x37, 0x63, 0x34, 0x30,
        0x37, 0x65, 0x39, 0x33, 0x32, 0x33, 0x38, 0x63, 0x63, 0x34, 0x34, 0x66, 0x39, 0x63, 0x65, 0x32,
        0x32, 0x64, 0x64, 0x02, 0x78, 0x28, 0x31, 0x30, 0x36, 0x31, 0x35, 0x61, 0x32, 0x64, 0x36, 0x36,
        0x37, 0x32, 0x30, 0x62, 0x37, 0x30, 0x65, 0x63, 0x61, 0x66, 0x61, 0x38, 0x39, 0x31, 0x61, 0x62,
        0x32, 0x36, 0x65, 0x39, 0x36, 0x61, 0x63, 0x39, 0x65, 0x65, 0x38, 0x31, 0x32, 0x65, 0x03, 0x78,
        0x40, 0x32, 0x63, 0x32, 0x35, 0x32, 0x34, 0x36, 0x64, 0x65, 0x31, 0x62, 0x35, 0x30, 0x31, 0x34,
        0x38, 0x64, 0x38, 0x31, 0x39, 0x33, 0x31, 0x36, 0x37, 0x38, 0x38, 0x30, 0x38, 0x32, 0x38, 0x38,
        0x31, 0x35, 0x62, 0x31, 0x37, 0x63, 0x38, 0x30, 0x65, 0x38, 0x65, 0x65, 0x36, 0x36, 0x61, 0x30,
        0x39, 0x64, 0x65, 0x63, 0x34, 0x35, 0x62, 0x31, 0x34, 0x33, 0x30, 0x31, 0x37, 0x38, 0x66, 0x63,
        0x31, 0x04, 0x41, 0x00, 0x05, 0x67, 0x41, 0x42, 0x53, 0x54, 0x41, 0x49, 0x4e, 0x06, 0x90, 0x6e,
        0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x70,
        0x72, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d,
        0x61, 0x74, 0x70, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
        0x70, 0x72, 0x65, 0x74, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x64,
        0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x71, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x74,
        0x72, 0x65, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x71, 0x70, 0x72, 0x69, 0x6d, 0x65,
        0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x6f, 0x70, 0x72, 0x69,
        0x6d, 0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x72, 0x63, 0x6f, 0x6d,
        0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x77,
        0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
        0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f,
        0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x78, 0x18, 0x63, 0x6f,
        0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x64, 0x69, 0x73,
        0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x75, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e,
        0x5f, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x75, 0x63, 0x6f, 0x6d,
        0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x70, 0x6f,
        0x73, 0x74, 0x73, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61,
        0x64, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x6d, 0x73, 0x77, 0x69, 0x66, 0x74, 0x5f, 0x76, 0x65, 0x72,
        0x73, 0x69, 0x6f, 0x6e, 0x71, 0x73, 0x77, 0x69, 0x66, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65,
        0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x07, 0x90, 0x78, 0x29, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f,
        0x48, 0x45, 0x41, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f,
        0x50, 0x4f, 0x53, 0x54, 0x5f, 0x34, 0x30, 0x5f, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x48, 0x45, 0x58,
        0x5f, 0x4c, 0x46, 0x78, 0x22, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43,
        0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f,
        0x53, 0x48, 0x41, 0x31, 0x5f, 0x4c, 0x46, 0x78, 0x25, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x53,
        0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x50, 0x4f,
        0x53, 0x54, 0x5f, 0x45, 0x58, 0x41, 0x43, 0x54, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x78, 0x22,
        0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x54, 0x52, 0x45, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f,
        0x56, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x52, 0x45, 0x50, 0x4c,
        0x41, 0x59, 0x78, 0x35, 0x50, 0x52, 0x49, 0x4d, 0x45, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x44,
        0x5f, 0x4d, 0x41, 0x4e, 0x49, 0x46, 0x45, 0x53, 0x54, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x53, 0x5f,
        0x52, 0x45, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f,
        0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x78, 0x33, 0x43, 0x4f, 0x4d, 0x50, 0x41,
        0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x45, 0x51,
        0x55, 0x41, 0x4c, 0x53, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53,
        0x5f, 0x50, 0x49, 0x4e, 0x4e, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x78, 0x26,
        0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
        0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x5f, 0x53,
        0x48, 0x41, 0x31, 0x5f, 0x4c, 0x46, 0x78, 0x29, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f,
        0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x41, 0x4e, 0x44,
        0x5f, 0x50, 0x4f, 0x53, 0x54, 0x5f, 0x45, 0x58, 0x41, 0x43, 0x54, 0x5f, 0x45, 0x4d, 0x50, 0x54,
        0x59, 0x78, 0x26, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x52, 0x45,
        0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x51, 0x55, 0x41,
        0x4c, 0x53, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x59, 0x78, 0x37, 0x43, 0x4f, 0x4d, 0x50, 0x41,
        0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x5f, 0x4d, 0x41, 0x4e, 0x49,
        0x46, 0x45, 0x53, 0x54, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
        0x45, 0x54, 0x45, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x55,
        0x52, 0x45, 0x78, 0x2d, 0x53, 0x57, 0x49, 0x46, 0x54, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f,
        0x4e, 0x5f, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x45, 0x44, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x49, 0x4e,
        0x47, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x49, 0x4e,
        0x44, 0x78, 0x33, 0x53, 0x57, 0x49, 0x46, 0x54, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f,
        0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x43, 0x41, 0x4e, 0x4f, 0x4e, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x46,
        0x52, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4e,
        0x54, 0x5f, 0x42, 0x49, 0x4e, 0x44, 0x78, 0x31, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x43, 0x4f,
        0x52, 0x45, 0x5f, 0x49, 0x4e, 0x44, 0x45, 0x50, 0x45, 0x4e, 0x44, 0x45, 0x4e, 0x54, 0x5f, 0x52,
        0x45, 0x50, 0x41, 0x52, 0x53, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x4c, 0x49, 0x56, 0x45, 0x5f,
        0x42, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x78, 0x2e, 0x46, 0x49, 0x4e, 0x41, 0x4c,
        0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x45, 0x41, 0x53,
        0x45, 0x5f, 0x4a, 0x4f, 0x55, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e,
        0x55, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x78, 0x1f, 0x46, 0x49, 0x4e, 0x41, 0x4c,
        0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x45, 0x52, 0x56,
        0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x78, 0x2b, 0x42, 0x55, 0x49, 0x4c,
        0x44, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x4f, 0x4c,
        0x45, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x53, 0x5f, 0x41,
        0x4c, 0x4c, 0x5f, 0x5a, 0x45, 0x52, 0x4f
    ]
    fileprivate static let sources: [FilePin] = [
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Control/gate-e-static-graph-registry.v1.json", size: 3113, digest: "d398b19918a779a2504a3a04ae72cd574da6caca6a8b27316b6b7f2dc3d89938", mode: 0o644, device: 16777231, inode: 18341422, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Package.swift", size: 1627, digest: "1cb536ecee3fbc6d2864047ec9db5d7af78921167ba25083c8831ac0cc7baa86", mode: 0o644, device: 16777231, inode: 18341423, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/ErgenticsGateECBORProjector/main.swift", size: 2109, digest: "d56a0b567bc9095f18997c7416735de8c1c9957889230154a20c57543c838a3f", mode: 0o644, device: 16777231, inode: 18341426, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/ErgenticsGateEDualGraphJoin/main.swift", size: 2388, digest: "5951953af6dc787a49216fdc942b116fc4ad8c76ded39a75a4d71265d19d720f", mode: 0o644, device: 16777231, inode: 18341428, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/ErgenticsGateEJSONProjector/main.swift", size: 2109, digest: "981c3e840f39859706571127ab4394b43ec409d57686c7acfbf20ffcf13c92ad", mode: 0o644, device: 16777231, inode: 18341430, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/GateECBORAuthority/GateECBORAuthority.swift", size: 27841, digest: "af84527ab2696131f36da89aaa2ec61d97368cb01c130783492eae4227319f82", mode: 0o644, device: 16777231, inode: 18341432, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/GateECBORAuthority/GateECBORReconstructor.swift", size: 30591, digest: "f600e1d2a412f761a2119d43b2421ed8368ac84de3825b44137d8588cf61d93e", mode: 0o644, device: 16777231, inode: 18341433, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/GateEDualGraphJoin/GateEDualGraphJoin.swift", size: 32655, digest: "32702cf823fdeb36eb348fbd82e0aa1620bd1e2efc06ee679717f039a53deae8", mode: 0o644, device: 16777231, inode: 18341435, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/GateEJSONAuthority/GateEJSONAuthority.swift", size: 27750, digest: "85802f3c91199f8726b504ee5bc1162efdefeea627e984e17e96bbe5b979b4dd", mode: 0o644, device: 16777231, inode: 18341437, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Sources/GateEJSONAuthority/GateEJSONReconstructor.swift", size: 12741, digest: "1f6f180aa117afc998ac944185256dd8f4c2fe91c05f56e9f8b5098f25d84f83", mode: 0o644, device: 16777231, inode: 18341438, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Tests/GateECBORAuthorityTests/GateECBORAuthorityTests.swift", size: 15541, digest: "8949257abdd6797cfc73933d775a05586ea47ab434bfc8d705835297463731b7", mode: 0o644, device: 16777231, inode: 18341441, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Tests/GateEDualGraphJoinTests/GateEDualGraphJoinTests.swift", size: 6494, digest: "2cc93d881b4aaf369d1755cff215b46c41f07728421bb0db258cb0b36d048322", mode: 0o644, device: 16777231, inode: 18341443, image: nil),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/source/Observability/ErgenticsGateEStaticControl/Tests/GateEJSONAuthorityTests/GateEJSONAuthorityTests.swift", size: 4248, digest: "798cef57134d3a61fd098b1ac69e32e283c35c2ad570f8ff30cb3a15edc7ecc3", mode: 0o644, device: 16777231, inode: 18341445, image: nil)
    ]
    fileprivate static let images: [FilePin] = [
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/scratch/arm64-apple-macosx/release/ErgenticsGateEJSONProjector", size: 185864, digest: "f77159f150e3704b26db5490c1750a0f2ace1332360eac6da7763a63b5ef90cb", mode: 0o755, device: 16777231, inode: 18341869, image: "1239EC62-146B-32FA-8812-19575C52E622"),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/scratch/arm64-apple-macosx/release/ErgenticsGateECBORProjector", size: 290136, digest: "9d6b2e218682070f6053a51f180f39892111e60081b4e4c9197b62bc03cd058b", mode: 0o755, device: 16777231, inode: 18341895, image: "AA3035CD-FE4D-3B97-9401-E5360CCF15DD"),
        FilePin(path: "/Users/ergentics/Documents/Codex/2026-08-09/resume-latin-roadmap-pr45/gate-e-static-release-builds-04c5324-2026-08-30-r1/A/scratch/arm64-apple-macosx/release/ErgenticsGateEDualGraphJoin", size: 160888, digest: "8ae0dfe19edf1c8583b097ce110cf785abf2ec92dcd0cde085745bc10829b7f2", mode: 0o755, device: 16777231, inode: 18341877, image: "71E66C53-B98C-3BCF-A0E8-12FB026C78F2")
    ]
}


private func checked(_ call: GEBSCallResult, _ operation: String) throws -> Int64 {
    try require(call.value >= 0 && call.error_number == 0 && call.cleanup_error_number == 0,
                "\(operation):rc=\(call.value):errno=\(call.error_number):cleanup=\(call.cleanup_error_number)")
    return call.value
}
private final class OwnedFD {
    private(set) var raw: Int32
    init(adopting raw: Int32) throws {
        try require(raw >= 0, "invalid descriptor")
        self.raw = raw
        if raw < 32 {
            let parked = gebs_park_descriptor(raw)
            let originalClose = gebs_close(raw)
            self.raw = -1
            if parked.value >= 0 && parked.value <= Int64(Int32.max) {
                self.raw = Int32(parked.value)
            }
            _ = try checked(parked, "park")
            _ = try checked(originalClose, "close unparked")
        }
        try require(self.raw >= 32, "FD parking")
    }
    convenience init(opened call: GEBSCallResult) throws {
        guard call.value >= 0 && call.value <= Int64(Int32.max) else {
            _ = try checked(call, "open"); throw BootstrapFailure.reject("descriptor range")
        }
        try self.init(adopting: Int32(call.value))
        _ = try checked(call, "open")
    }
    func closeChecked() throws {
        let value = raw
        raw = -1
        if value >= 0 { _ = try checked(gebs_close(value), "close") }
    }
    deinit { if raw >= 0 { _ = gebs_close(raw) } }
}
private struct Metadata: Equatable {
    let vnode: Vnode
    let type: UInt32
    let mode: UInt32
    let uid: UInt32
    let gid: UInt32
    let nlink: UInt64
    let size: Int64
    let mtimeSeconds: Int64
    let mtimeNanoseconds: Int64
    let ctimeSeconds: Int64
    let ctimeNanoseconds: Int64
    init(_ raw: GEBSStat) {
        vnode = Vnode(device: raw.device, inode: raw.inode)
        type = raw.file_type; mode = raw.mode; uid = raw.uid; gid = raw.gid
        nlink = raw.nlink; size = raw.size
        mtimeSeconds = raw.mtime_seconds; mtimeNanoseconds = raw.mtime_nanoseconds
        ctimeSeconds = raw.ctime_seconds; ctimeNanoseconds = raw.ctime_nanoseconds
    }
    static func descriptor(_ fd: Int32) throws -> Self {
        let result = gebs_stat(fd)
        _ = try checked(result.call, "fstat")
        return Self(result.metadata)
    }
    static func named(_ parent: Int32, _ leaf: String) throws -> Self {
        let result = leaf.withCString { gebs_stat_at(parent, $0) }
        _ = try checked(result.call, "fstatat")
        return Self(result.metadata)
    }
    func sameDirectoryIdentity(as other: Self) -> Bool {
        vnode == other.vnode && type == other.type && mode == other.mode && uid == other.uid && gid == other.gid
    }
    func sameLeafIdentity(as other: Self) -> Bool {
        sameDirectoryIdentity(as: other) && nlink == other.nlink
    }
    func requireFile(mode expectedMode: UInt32, uid expectedUID: UInt32) throws {
        try require(type == 0o100000 && mode == expectedMode && uid == expectedUID &&
                    nlink == 1 && size >= 0 && mtimeNanoseconds >= 0 && mtimeNanoseconds < 1_000_000_000 &&
                    ctimeNanoseconds >= 0 && ctimeNanoseconds < 1_000_000_000, "file metadata")
    }
}
private func names(_ fd: Int32) throws -> [String] {
    var bytes = [UInt8](repeating: 0, count: 65_536)
    let result = bytes.withUnsafeMutableBytes { gebs_directory_names(fd, $0.baseAddress, $0.count) }
    let count = try checked(result.call, "directory names")
    try require(result.close_result == 0 && result.close_error_number == 0 &&
                count <= Int64(bytes.count), "directory listing close/size")
    bytes.removeSubrange(Int(count)..<bytes.count)
    if bytes.isEmpty { return [] }
    try require(bytes.last == 0, "directory listing framing")
    let parts = bytes.dropLast().split(separator: 0, omittingEmptySubsequences: false)
    let resultNames = try parts.map { part -> String in
        try require(!part.isEmpty && !part.contains(47), "directory component")
        guard let value = String(bytes: part, encoding: .utf8) else {
            throw BootstrapFailure.reject("non-UTF8 directory entry")
        }
        return value
    }
    try require(Set(resultNames).count == resultNames.count, "duplicate directory name")
    return resultNames.sorted()
}
private struct DirectoryNode {
    let fd: OwnedFD
    let parent: OwnedFD?
    let leaf: String?
    let admitted: Metadata
}
private final class DirectoryArena {
    // One Run-owned descriptor per absolute directory, never a process-global
    // cache. Sharing holds prevents per-file ancestor amplification/EMFILE.
    var nodes: [String: DirectoryNode] = [:]
    init() throws {
        let root = try OwnedFD(opened: gebs_open_root_directory())
        let metadata = try Metadata.descriptor(root.raw)
        nodes["/"] = DirectoryNode(fd: root, parent: nil, leaf: nil, admitted: metadata)
    }
}
private final class DirectoryChain {
    let nodes: [DirectoryNode]
    var last: OwnedFD { nodes[nodes.count - 1].fd }
    init(path: String, arena: DirectoryArena) throws {
        try require(path.first == "/" && !path.contains("\0"), "fixed absolute directory")
        var built: [DirectoryNode] = []
        let root = arena.nodes["/"]!
        try Self.checkDirectory(root.admitted)
        built.append(root)
        var prefix = ""
        for component in path.split(separator: "/").map(String.init) {
            try require(component != "." && component != "..", "directory traversal")
            let parent = built[built.count - 1].fd
            prefix += "/" + component
            if let cached = arena.nodes[prefix] {
                built.append(cached)
                continue
            }
            let fd = try OwnedFD(opened: component.withCString { gebs_open_directory_at(parent.raw, $0) })
            let metadata = try Metadata.descriptor(fd.raw)
            try Self.checkDirectory(metadata)
            try require(try Metadata.named(parent.raw, component).sameDirectoryIdentity(as: metadata),
                        "directory named join")
            let node = DirectoryNode(fd: fd, parent: parent, leaf: component, admitted: metadata)
            arena.nodes[prefix] = node
            built.append(node)
        }
        nodes = built
        try validate()
    }
    private static func checkDirectory(_ metadata: Metadata) throws {
        try require(metadata.type == 0o40000 && metadata.mode & 0o022 == 0 &&
                    (metadata.uid == 0 || metadata.uid == gebs_effective_uid()), "directory admission")
    }
    func validate() throws {
        for node in nodes {
            let current = try Metadata.descriptor(node.fd.raw)
            try Self.checkDirectory(current)
            try require(current.sameDirectoryIdentity(as: node.admitted), "held parent changed")
            if let parent = node.parent, let leaf = node.leaf {
                try require(try Metadata.named(parent.raw, leaf).sameDirectoryIdentity(as: current),
                            "parent named rebound")
            }
        }
    }
}
private struct Capture: Equatable {
    let metadata: Metadata
    let digest: String
    let bytes: [UInt8]
}
private func readCapture(fd: OwnedFD, parent: OwnedFD, leaf: String, cap: Int,
                         mode: UInt32) throws -> Capture {
    let before = try Metadata.descriptor(fd.raw)
    try before.requireFile(mode: mode, uid: gebs_effective_uid())
    try require(before.size <= Int64(cap), "capture cap")
    var bytes = [UInt8](repeating: 0, count: Int(before.size))
    var offset = 0
    while offset < bytes.count {
        let result = bytes.withUnsafeMutableBytes {
            gebs_pread(fd.raw, $0.baseAddress!.advanced(by: offset), $0.count - offset, Int64(offset))
        }
        if result.value < 0 && result.error_number == 4 { continue }
        let count = try checked(result, "pread")
        try require(count > 0 && count <= Int64(bytes.count - offset), "short pread")
        offset += Int(count)
    }
    var extra: UInt8 = 0
    let eof = gebs_pread(fd.raw, &extra, 1, Int64(bytes.count))
    try require(try checked(eof, "finite EOF") == 0, "file grew")
    let after = try Metadata.descriptor(fd.raw)
    let named = try Metadata.named(parent.raw, leaf)
    try require(before == after && after == named, "file read/name continuity")
    return Capture(metadata: after, digest: bootstrapSHA256(bytes), bytes: bytes)
}
private func writeAll(_ bytes: [UInt8], _ fd: OwnedFD) throws {
    var offset = 0
    while offset < bytes.count {
        let call = bytes.withUnsafeBytes {
            gebs_write(fd.raw, $0.baseAddress!.advanced(by: offset), $0.count - offset)
        }
        if call.value < 0 && call.error_number == 4 { continue }
        let count = try checked(call, "write")
        try require(count > 0 && count <= Int64(bytes.count - offset), "short write")
        offset += Int(count)
    }
}

private enum MachO {
    // Thin arm64, little-endian MH_EXECUTE. All load-command traversal is over
    // held, byte-hashed image bytes. No analyzer subprocesses.
    static func verify(_ bytes: [UInt8], uuid: String) throws {
        func u32(_ offset: Int) throws -> UInt32 {
            try require(offset >= 0 && offset <= bytes.count && 4 <= bytes.count - offset, "Mach-O range")
            return (0..<4).reduce(UInt32(0)) { $0 | (UInt32(bytes[offset + $1]) << (8 * $1)) }
        }
        try require(bytes.count >= 32, "Mach-O header")
        try require(try u32(0) == 0xfeedfacf && u32(4) == 0x0100000c && u32(12) == 2, "Mach-O identity")
        let count = Int(try u32(16)), commandBytes = Int(try u32(20))
        try require(count > 0 && count <= 4096 && commandBytes <= bytes.count - 32, "Mach-O commands")
        let end = 32 + commandBytes
        var offset = 32
        var seenUUID = false, seenVersion = false
        for _ in 0..<count {
            let command = try u32(offset), size = Int(try u32(offset + 4))
            try require(size >= 8 && size % 8 == 0 && offset <= end && size <= end - offset, "Mach-O command size")
            if command == 0x1b {
                try require(!seenUUID && size == 24, "Mach-O UUID count")
                let hex = bytes[(offset + 8)..<(offset + 24)].map { String(format: "%02X", $0) }.joined()
                try require(hex == uuid.replacingOccurrences(of: "-", with: ""), "Mach-O UUID")
                seenUUID = true
            }
            if command == 0x32 {
                try require(!seenVersion && size >= 24, "Mach-O build version count")
                try require(try u32(offset + 8) == 1 && u32(offset + 12) == 0x000e0000 &&
                            u32(offset + 16) == 0x001a0500, "Mach-O platform/minimum/SDK")
                let tools = Int(try u32(offset + 20))
                try require(tools <= 4096 && size == 24 + 8 * tools, "Mach-O tool table")
                seenVersion = true
            }
            offset += size
        }
        try require(offset == end && seenUUID && seenVersion, "Mach-O complete commands")
    }
}
private final class HeldFile {
    let pin: FilePin
    let parents: DirectoryChain
    let leaf: String
    let fd: OwnedFD
    let baseline: Capture
    init(_ pin: FilePin, arena: DirectoryArena) throws {
        guard let slash = pin.path.lastIndex(of: "/") else { throw BootstrapFailure.reject("pin path") }
        let heldLeaf = String(pin.path[pin.path.index(after: slash)...])
        let heldParents = try DirectoryChain(path: String(pin.path[..<slash]), arena: arena)
        let heldFD = try OwnedFD(opened: heldLeaf.withCString { gebs_open_regular_read_at(heldParents.last.raw, $0) })
        let observed = try readCapture(fd: heldFD, parent: heldParents.last, leaf: heldLeaf, cap: pin.size, mode: pin.mode)
        try require(observed.bytes.count == pin.size && observed.digest == pin.digest, "pinned bytes")
        if let device = pin.device, let inode = pin.inode {
            try require(observed.metadata.vnode == Vnode(device: device, inode: inode), "saved vnode")
        }
        if let uuid = pin.image { try MachO.verify(observed.bytes, uuid: uuid) }
        try heldParents.validate()
        self.pin = pin; leaf = heldLeaf; parents = heldParents; fd = heldFD; baseline = observed
    }
    func validate() throws -> Capture {
        try parents.validate()
        let current = try readCapture(fd: fd, parent: parents.last, leaf: leaf, cap: pin.size, mode: pin.mode)
        try require(current == baseline, "immutable admission changed")
        if let uuid = pin.image { try MachO.verify(current.bytes, uuid: uuid) }
        return current
    }
}


private struct InventoryEntry {
    let chain: DirectoryChain
    let children: [String]
    let admitted: Metadata
}
private final class SourceInventory {
    let entries: [InventoryEntry]
    init(arena: DirectoryArena) throws {
        var expected: [String: Set<String>] = [:]
        for pin in StaticPins.sources {
            let prefix = StaticPins.sourceRoot + "/"
            try require(pin.path.hasPrefix(prefix), "source inventory root")
            let parts = pin.path.dropFirst(prefix.count).split(separator: "/").map(String.init)
            var directory = StaticPins.sourceRoot
            for component in parts {
                expected[directory, default: []].insert(component)
                directory += "/" + component
            }
        }
        entries = try expected.keys.sorted().map { path in
            let chain = try DirectoryChain(path: path, arena: arena)
            let before = try Metadata.descriptor(chain.last.raw)
            let children = try names(chain.last.raw)
            try require(children == expected[path]!.sorted(), "exact thirteen-file source topology")
            try require(try Metadata.descriptor(chain.last.raw) == before, "source inventory changed")
            return InventoryEntry(chain: chain, children: children, admitted: before)
        }
    }
    func validate() throws {
        for entry in entries {
            try entry.chain.validate()
            try require(try Metadata.descriptor(entry.chain.last.raw) == entry.admitted &&
                        names(entry.chain.last.raw) == entry.children &&
                        Metadata.descriptor(entry.chain.last.raw) == entry.admitted, "source topology continuity")
        }
    }
}
private final class RunRoot {
    let parent: DirectoryChain
    let fd: OwnedFD
    let workspace: OwnedFD
    let admitted: Metadata
    let workspaceAdmitted: Metadata
    private(set) var leaves: Set<String> = ["workspace"]
    init(arena: DirectoryArena) throws {
        let heldParent = try DirectoryChain(path: StaticPins.parentPath, arena: arena)
        _ = try checked(gebs_set_private_umask(), "private umask")
        _ = try checked(gebs_create_run_root(heldParent.last.raw), "exclusive run root")
        let heldFD = try OwnedFD(opened: StaticPins.runLeaf.withCString { gebs_open_directory_at(heldParent.last.raw, $0) })
        let rootMetadata = try Metadata.descriptor(heldFD.raw)
        try require(rootMetadata.type == 0o40000 && rootMetadata.mode == 0o700 &&
                    rootMetadata.uid == gebs_effective_uid(), "run root metadata")
        try require(try Metadata.named(heldParent.last.raw, StaticPins.runLeaf) == rootMetadata && names(heldFD.raw).isEmpty,
                    "new run root join/empty")
        _ = try checked(gebs_sync(heldParent.last.raw), "run root parent sync")
        _ = try checked(gebs_create_workspace(heldFD.raw), "exclusive workspace")
        let heldWorkspace = try OwnedFD(opened: "workspace".withCString { gebs_open_directory_at(heldFD.raw, $0) })
        let workspaceMetadata = try Metadata.descriptor(heldWorkspace.raw)
        try require(workspaceMetadata.type == 0o40000 && workspaceMetadata.mode == 0o700 &&
                    workspaceMetadata.uid == gebs_effective_uid(), "workspace metadata")
        _ = try checked(gebs_sync(heldFD.raw), "workspace parent sync")
        parent = heldParent; fd = heldFD; admitted = rootMetadata
        workspace = heldWorkspace; workspaceAdmitted = workspaceMetadata
        try validate()
    }
    func create(_ leaf: String) throws -> OwnedFD {
        try require(!leaves.contains(leaf), "duplicate leaf")
        let result = leaf.withCString { gebs_create_leaf(fd.raw, $0) }
        // Account for the new name immediately if open succeeded, even if later
        // metadata/sync/close fails. Retention never removes a partial leaf.
        if result.value >= 0 { leaves.insert(leaf) }
        let created = try OwnedFD(opened: result)
        let metadata = try Metadata.descriptor(created.raw)
        try metadata.requireFile(mode: 0o600, uid: gebs_effective_uid())
        try require(metadata.size == 0 && Metadata.named(fd.raw, leaf) == metadata, "exclusive empty leaf")
        return created
    }
    func freshRead(_ leaf: String, expected: Capture) throws -> OwnedFD {
        let opened = try OwnedFD(opened: leaf.withCString { gebs_open_regular_read_at(fd.raw, $0) })
        let observed = try readCapture(fd: opened, parent: fd, leaf: leaf, cap: expected.bytes.count, mode: 0o600)
        try require(observed == expected, "fresh read-only descriptor join")
        try EndpointChecks.input(offset: checked(gebs_cursor(opened.raw), "input cursor"),
                                 readOnly: checked(gebs_access_mode(opened.raw), "input access") == 0,
                                 sourceFD: opened.raw, targetFD: 0)
        return opened
    }
    func validate() throws {
        try parent.validate()
        try require(try Metadata.descriptor(fd.raw).sameDirectoryIdentity(as: admitted) &&
                    Metadata.named(parent.last.raw, StaticPins.runLeaf).sameDirectoryIdentity(as: admitted),
                    "run root rebound")
        try require(try Metadata.descriptor(workspace.raw) == workspaceAdmitted &&
                    Metadata.named(fd.raw, "workspace") == workspaceAdmitted && names(workspace.raw).isEmpty,
                    "workspace changed")
        try require(try Set(names(fd.raw)) == leaves, "unexpected runtime entry")
    }
}
private final class RuntimeLeaf {
    let root: RunRoot
    let name: String
    let cap: Int
    private(set) var fd: OwnedFD
    private let created: Metadata
    private(set) var sealed: Capture?
    init(root: RunRoot, name: String, cap: Int) throws {
        self.root = root; self.name = name; self.cap = cap
        fd = try root.create(name)
        created = try Metadata.descriptor(fd.raw)
    }
    func writeInput(_ bytes: [UInt8]) throws {
        try require(sealed == nil && bytes.count <= cap, "input write state")
        try writeAll(bytes, fd)
        let captured = try sealAfterReapOrInputWrite()
        try require(captured.bytes == bytes, "input readback")
    }
    @discardableResult
    func sealAfterReapOrInputWrite() throws -> Capture {
        try require(sealed == nil, "capture already sealed")
        let observed = try readCapture(fd: fd, parent: root.fd, leaf: name, cap: cap, mode: 0o600)
        try require(observed.metadata.sameLeafIdentity(as: created), "output replacement")
        _ = try checked(gebs_sync(fd.raw), "capture sync")
        _ = try checked(gebs_sync(root.fd.raw), "capture name sync")
        try require(try readCapture(fd: fd, parent: root.fd, leaf: name, cap: cap, mode: 0o600) == observed,
                    "capture changed around sync")
        try fd.closeChecked()
        // Writer descriptions are gone before any later role receives a fresh
        // read-only description. The retained reader itself is never rewound.
        fd = try root.freshRead(name, expected: observed)
        sealed = observed
        return observed
    }
    func validate() throws -> Capture {
        let current = try readCapture(fd: fd, parent: root.fd, leaf: name, cap: cap, mode: 0o600)
        if let sealed { try require(current == sealed, "sealed capture changed") }
        else { try require(current.metadata == created && current.bytes.isEmpty, "unentered output changed") }
        return current
    }
}
// This encoder writes only control observations, never worker/graph receipts.
private indirect enum Observation {
    case text(String), signed(Int64), unsigned(UInt64), flag(Bool), null
    case array([Observation]), object([String: Observation])
    var encoded: String {
        switch self {
        case .text(let string):
            let escaped = string.unicodeScalars.map { scalar -> String in
                switch scalar.value {
                case 34: return "\\\""
                case 92: return "\\\\"
                case 0...31: return String(format: "\\u%04x", scalar.value)
                default: return String(scalar)
                }
            }.joined()
            return "\"" + escaped + "\""
        case .signed(let number): return String(number)
        case .unsigned(let number): return String(number)
        case .flag(let bool): return bool ? "true" : "false"
        case .null: return "null"
        case .array(let entries): return "[" + entries.map(\.encoded).joined(separator: ",") + "]"
        case .object(let fields):
            return "{" + fields.keys.sorted().map { Observation.text($0).encoded + ":" + fields[$0]!.encoded }.joined(separator: ",") + "}"
        }
    }
}
private extension Metadata {
    var observation: Observation {
        .object([
            "ctime_nanoseconds": .signed(ctimeNanoseconds), "ctime_seconds": .signed(ctimeSeconds),
            "device": .unsigned(vnode.device), "file_type": .unsigned(UInt64(type)),
            "gid": .unsigned(UInt64(gid)), "inode": .unsigned(vnode.inode), "mode": .unsigned(UInt64(mode)),
            "mtime_nanoseconds": .signed(mtimeNanoseconds), "mtime_seconds": .signed(mtimeSeconds),
            "nlink": .unsigned(nlink), "size": .signed(size), "uid": .unsigned(UInt64(uid)),
        ])
    }
}
private extension Capture {
    func rawObservation(name: String) -> Observation {
        .object(["metadata": metadata.observation, "name": .text(name), "sha256": .text(digest)])
    }
}
private func rawObservation(_ call: GEBSCallResult) -> Observation {
    .object(["cleanup_errno": .signed(Int64(call.cleanup_error_number)), "entered": .signed(Int64(call.entered)),
             "errno": .signed(Int64(call.error_number)), "return": .signed(call.value)])
}
private func rawObservation(_ clock: GEBSClockSample) -> Observation {
    .object(["denominator": .unsigned(UInt64(clock.denominator)), "kernel_result": .signed(Int64(clock.kernel_result)),
             "numerator": .unsigned(UInt64(clock.numerator)), "ticks": .unsigned(clock.ticks)])
}
private func rawObservation(_ spawn: GEBSSpawnResult) -> Observation {
    .object([
        "actions_destroy_entered": .signed(Int64(spawn.actions_destroy_entered)),
        "actions_destroy_result": .signed(Int64(spawn.actions_destroy_result)),
        "attributes_destroy_entered": .signed(Int64(spawn.attributes_destroy_entered)),
        "attributes_destroy_result": .signed(Int64(spawn.attributes_destroy_result)),
        "pid": .signed(Int64(spawn.pid)), "setup_error": .signed(Int64(spawn.setup_error)),
        "setup_step": .signed(Int64(spawn.setup_step)), "spawn_entered": .signed(Int64(spawn.spawn_entered)),
        "spawn_result": .signed(Int64(spawn.spawn_result)),
    ])
}
private final class Journal {
    let root: RunRoot
    private var head: (name: String, capture: Capture)?
    private var records: [(name: String, capture: Capture, fd: OwnedFD)] = []
    private(set) var terminalAttempted = false
    init(root: RunRoot) { self.root = root }
    func publish(_ leaf: String, fields: [String: Observation]) throws {
        if leaf == "90-terminal.json" {
            try require(!terminalAttempted, "terminal attempt consumed")
            terminalAttempted = true
        }
        try validate()
        var record = fields
        record["schema"] = .text("ergentics.gate-e.static.bootstrap-observation.v1")
        record["authority_vector"] = .text("00000000")
        record["projection_write_mask"] = .text("00000000")
        record["gate_e"] = .text("ABSTAIN")
        record["control_commit"] = .text(StaticPins.controlCommit)
        record["control_sha256"] = .text(StaticPins.controlDigest)
        record["historical_pre_B_metadata"] = .text("UNOBSERVED")
        record["historical_build_sequence"] = .text("FAIL_PRE_B_METADATA_CHECK_OMITTED")
        record["previous_leaf"] = head.map { .text($0.name) } ?? .null
        record["previous_sha256"] = head.map { .text($0.capture.digest) } ?? .null
        let bytes = Array(Observation.object(record).encoded.utf8)
        try require(bytes.count <= 262_144, "observation cap")
        let fd = try root.create(leaf)
        try writeAll(bytes, fd)
        let captured = try readCapture(fd: fd, parent: root.fd, leaf: leaf, cap: 262_144, mode: 0o600)
        try require(captured.bytes == bytes, "observation readback")
        _ = try checked(gebs_sync(fd.raw), "observation sync")
        _ = try checked(gebs_sync(root.fd.raw), "observation name sync")
        try require(try readCapture(fd: fd, parent: root.fd, leaf: leaf, cap: 262_144, mode: 0o600) == captured,
                    "observation changed at sync")
        try fd.closeChecked()
        let reader = try root.freshRead(leaf, expected: captured)
        // Advance ancestry only after complete publication/readback/sync/close.
        records.append((leaf, captured, reader))
        head = (leaf, captured)
    }
    func validate() throws {
        try root.validate()
        for record in records {
            try require(try readCapture(fd: record.fd, parent: root.fd, leaf: record.name,
                                        cap: 262_144, mode: 0o600) == record.capture, "retained journal changed")
        }
    }
}
private struct BoundaryCut: Equatable {
    let source: [Capture]
    let images: [Capture]
    let control: Capture
    let endpoints: [String: Capture]
    var observation: Observation {
        .object([
            "source": .array(zip(StaticPins.sources, source).map { $1.rawObservation(name: $0.path) }),
            "images": .array(zip(StaticPins.images, images).map { $1.rawObservation(name: $0.path) }),
            "control": control.rawObservation(name: StaticPins.controlPath),
            "endpoints": .array(endpoints.keys.sorted().map { endpoints[$0]!.rawObservation(name: $0) }),
        ])
    }
}
private final class StageEndpoints {
    let stage: Stage
    let inputs: [Int32: OwnedFD]
    let outputs: [Int32: RuntimeLeaf]
    let workspace: OwnedFD
    private let root: RunRoot
    private let inputBaselines: [Int32: Capture]
    init(stage: Stage, root: RunRoot, retained: inout [String: RuntimeLeaf]) throws {
        self.stage = stage; workspace = root.workspace; self.root = root
        var readers: [Int32: OwnedFD] = [:]
        var writers: [Int32: RuntimeLeaf] = [:]
        var baselines: [Int32: Capture] = [:]
        for (target, name) in stage.inputs.sorted(by: { $0.key < $1.key }) {
            guard let capture = retained[name]?.sealed else { throw BootstrapFailure.reject("missing sealed input") }
            readers[target] = try root.freshRead(name, expected: capture)
            baselines[target] = capture
        }
        for (target, name) in stage.outputs.sorted(by: { $0.key < $1.key }) {
            let cap = target == 2 ? 65_536 : ((target == 3 && stage != .join) || target == 8 ? 16_777_216 : 262_144)
            let leaf = try RuntimeLeaf(root: root, name: name, cap: cap)
            retained[name] = leaf
            writers[target] = leaf
        }
        inputs = readers; outputs = writers; inputBaselines = baselines
        try validate()
    }
    func validate() throws {
        try EndpointChecks.plan(stage: stage, inputs: inputs.mapValues(\.raw), outputs: outputs.mapValues { $0.fd.raw })
        var inputNodes: [Vnode] = []
        for (target, fd) in inputs {
            try EndpointChecks.input(offset: checked(gebs_cursor(fd.raw), "role input offset"),
                                     readOnly: checked(gebs_access_mode(fd.raw), "role input mode") == 0,
                                     sourceFD: fd.raw, targetFD: target)
            let expected = inputBaselines[target]!
            let captured = try readCapture(fd: fd, parent: root.fd, leaf: stage.inputs[target]!,
                                           cap: expected.bytes.count, mode: 0o600)
            try require(captured == expected, "role input complete snapshot join")
            inputNodes.append(captured.metadata.vnode)
        }
        let outputNodes = try outputs.values.map { leaf -> Vnode in
            try require(leaf.sealed == nil, "role output already consumed")
            return try leaf.validate().metadata.vnode
        }
        try EndpointChecks.disjoint(inputs: inputNodes, outputs: outputNodes)
    }
    func closeInputs() throws { for key in inputs.keys.sorted() { try inputs[key]!.closeChecked() } }
    func projectorFDs() -> GEBSProjectorFDs {
        GEBSProjectorFDs(cwd: workspace.raw, input: inputs[0]!.raw,
                        verifier: outputs[1]!.fd.raw, stderr_file: outputs[2]!.fd.raw,
                        graph: outputs[3]!.fd.raw, roundtrip: outputs[4]!.fd.raw)
    }
    func joinFDs() -> GEBSJoinFDs {
        GEBSJoinFDs(cwd: workspace.raw, json_graph: inputs[0]!.raw,
                   json_verifier: inputs[3]!.raw, json_roundtrip: inputs[4]!.raw,
                   cbor_graph: inputs[5]!.raw, cbor_verifier: inputs[6]!.raw, cbor_roundtrip: inputs[7]!.raw,
                   receipt: outputs[1]!.fd.raw, stderr_file: outputs[2]!.fd.raw, graph: outputs[8]!.fd.raw)
    }
}


private final class FullBoundaryAdmission {
    let stage: Stage
    let cut: BoundaryCut
    private let owner: Run
    private let endpoints: StageEndpoints
    private let start: GEBSClockSample
    private let once = OneShotLatch()
    private init(owner: Run, endpoints: StageEndpoints, cut: BoundaryCut, start: GEBSClockSample) {
        self.owner = owner; self.endpoints = endpoints; self.cut = cut; stage = endpoints.stage
        self.start = start
    }
    static func prepare(owner: Run, endpoints: StageEndpoints, expected: BoundaryCut, start: GEBSClockSample) throws -> FullBoundaryAdmission {
        try endpoints.validate()
        let current = try owner.captureBoundary()
        try require(current == expected, "admission changed after durable entry record")
        return FullBoundaryAdmission(owner: owner, endpoints: endpoints, cut: current, start: start)
    }
    private func checkDeadline() throws {
        let current = gebs_clock_sample()
        try require(current.kernel_result == 0 && current.numerator == start.numerator &&
                    current.denominator == start.denominator, "pre-entry clock continuity")
        try require(try !Deadline.expired(start: start.ticks, now: current.ticks,
                                         numerator: start.numerator, denominator: start.denominator), "expired before spawn")
    }
    // Three distinct consumers, no caller argv/env/cwd/role/timeout parameters.
    func consumeJSON() throws -> GEBSSpawnResult {
        try once.consume(); try require(stage == .json, "JSON token stage")
        var descriptors = endpoints.projectorFDs(), result = GEBSSpawnResult()
        try checkDeadline()
        gebs_spawn_json(&descriptors, &result)
        return result
    }
    func consumeCBOR() throws -> GEBSSpawnResult {
        try once.consume(); try require(stage == .cbor, "CBOR token stage")
        var descriptors = endpoints.projectorFDs(), result = GEBSSpawnResult()
        try checkDeadline()
        gebs_spawn_cbor(&descriptors, &result)
        return result
    }
    func consumeJOIN() throws -> GEBSSpawnResult {
        try once.consume(); try require(stage == .join, "JOIN token stage")
        var descriptors = endpoints.joinFDs(), result = GEBSSpawnResult()
        try checkDeadline()
        gebs_spawn_join(&descriptors, &result)
        return result
    }
}
private final class OwnedChild {
    private(set) var state: ChildOwnership
    let start: GEBSClockSample
    private(set) var end: GEBSClockSample?
    private(set) var finalWait: GEBSWaitResult?
    private(set) var kill: GEBSCallResult?
    private(set) var lastPause: GEBSCallResult?
    private(set) var rejected = false
    private var runningReturns: UInt64 = 0
    private var interruptedReturns: UInt64 = 0
    private var pauseEntries: UInt64 = 0
    private var pauseInterruptions: UInt64 = 0
    private var countOverflow = false
    init(pid: Int32, start: GEBSClockSample) throws {
        state = try ChildOwnership(pid: pid)
        self.start = start
    }
    private func increment(_ value: inout UInt64) {
        let (next, overflow) = value.addingReportingOverflow(1)
        if overflow { countOverflow = true; rejected = true } else { value = next }
    }
    // Nothing in this loop throws past an owned unreaped PID. After KILL entry,
    // blocking exact reap is deliberately allowed to remain nonterminal.
    func finish(forceDisposal: Bool) {
        if state.isReaped || state.ownershipLost { return }
        var disposal = forceDisposal
        if forceDisposal { rejected = true }
        while !state.isReaped && !state.ownershipLost {
            let wait = state.killCommitted ? gebs_reap_exact(state.pid) : gebs_wait_exact_nonblocking(state.pid)
            finalWait = wait
            do {
                if wait.call.value == Int64(state.pid) && wait.call.error_number == 0 {
                    // An exact-PID traced stop is not a reap. Do not grant
                    // conservation or signal authority from a nonterminal
                    // status merely because waitpid returned the target PID.
                    guard (wait.exited == 1) != (wait.signaled == 1) else {
                        try state.observe(.lost(-2))
                        rejected = true
                        end = gebs_clock_sample()
                        break
                    }
                    try state.observe(.reaped(wait.status))
                    end = gebs_clock_sample()
                    if let end {
                        if end.kernel_result != 0 || end.numerator != start.numerator || end.denominator != start.denominator {
                            rejected = true
                        } else {
                            do {
                                if try Deadline.expired(start: start.ticks, now: end.ticks,
                                                        numerator: start.numerator, denominator: start.denominator) {
                                    rejected = true
                                }
                            } catch { rejected = true }
                        }
                    }
                    break
                } else if wait.call.value == 0 && wait.call.error_number == 0 {
                    increment(&runningReturns)
                    try state.observe(.running)
                } else if wait.call.value == -1 && wait.call.error_number == 4 {
                    increment(&interruptedReturns)
                    try state.observe(.interrupted)
                } else {
                    try state.observe(.lost(wait.call.error_number))
                    rejected = true
                    end = gebs_clock_sample()
                    break
                }
            } catch {
                // Only a pure state inconsistency can reach this branch. Never
                // signal a slot whose exclusive ownership is no longer proved.
                rejected = true
                return
            }
            if state.killCommitted { continue } // EINTR after blocking reap.
            let clock = gebs_clock_sample()
            do {
                try require(clock.kernel_result == 0 && clock.numerator == start.numerator &&
                            clock.denominator == start.denominator, "clock continuity")
                if try Deadline.expired(start: start.ticks, now: clock.ticks,
                                        numerator: start.numerator, denominator: start.denominator) {
                    disposal = true; rejected = true
                }
            } catch { disposal = true; rejected = true }
            if disposal {
                do {
                    // Commit in memory BEFORE native entry; never repeat on any
                    // returned errno, including EINTR or ESRCH.
                    let exactPID = try state.commitKill()
                    kill = gebs_kill_exact(exactPID)
                } catch { rejected = true; return }
                continue
            }
            let pause = gebs_poll_pause()
            lastPause = pause
            increment(&pauseEntries)
            if pause.value < 0 && pause.error_number == 4 { increment(&pauseInterruptions) }
            else if pause.value != 0 || pause.error_number != 0 { disposal = true; rejected = true }
        }
    }
    var normalSuccess: Bool {
        guard state.isReaped, !state.ownershipLost, !state.killCommitted, !rejected,
              let finalWait, let end else { return false }
        return finalWait.exited == 1 && finalWait.exit_code == 0 && finalWait.signaled == 0 &&
               end.kernel_result == 0 && end.numerator == start.numerator && end.denominator == start.denominator &&
               end.ticks >= start.ticks
    }
    var observation: Observation {
        var fields: [String: Observation] = [
            "count_overflow": .flag(countOverflow), "end": end.map { rawObservation($0) } ?? .null,
            "exact_reaped": .flag(state.isReaped), "kill": kill.map { rawObservation($0) } ?? .null,
            "kill_committed": .flag(state.killCommitted), "last_pause": lastPause.map { rawObservation($0) } ?? .null,
            "normal_exit_zero": .flag(normalSuccess), "ownership_lost": .flag(state.ownershipLost),
            "pause_entries": .unsigned(pauseEntries), "pause_EINTR_returns": .unsigned(pauseInterruptions),
            "pid": .signed(Int64(state.pid)), "rejected": .flag(rejected), "start": rawObservation(start),
            "wait_EINTR_returns": .unsigned(interruptedReturns), "wait_zero_returns": .unsigned(runningReturns),
            "wait_poll_trace_scope": .text("Exact result-class counts; individual polling timestamps/order not retained"),
            "descendant_or_group_conservation": .text("NOT_CLAIMED"),
        ]
        if let wait = finalWait {
            fields["last_wait"] = .object([
                "call": rawObservation(wait.call), "exit_code": .signed(Int64(wait.exit_code)),
                "exited": .signed(Int64(wait.exited)), "signaled": .signed(Int64(wait.signaled)),
                "status": .signed(Int64(wait.status)), "term_signal": .signed(Int64(wait.term_signal)),
            ])
        } else { fields["last_wait"] = .null }
        return .object(fields)
    }
}
private final class Run {
    private var directoryArena: DirectoryArena?
    private var sources: [HeldFile] = []
    private var images: [HeldFile] = []
    private var control: HeldFile?
    private var inventory: SourceInventory?
    private var root: RunRoot?
    private var journal: Journal?
    private var retained: [String: RuntimeLeaf] = [:]
    private var sequencer = StageSequencer()
    private var active: OwnedChild?
    private var lastSpawn: GEBSSpawnResult?
    private var enteredStage: Stage?
    private var audits: [Observation] = []
    private var jsonBinding: GraphBinding?
    private var cborBinding: GraphBinding?

    func execute() throws {
        // Byte-identical build candidates are freshly admitted, not promoted
        // from the historical build's missing pre-B metadata observation.
        try require(bootstrapSHA256(StaticPins.jsonBytes) == Codec.json.candidateHash &&
                    bootstrapSHA256(StaticPins.cborBytes) == Codec.cbor.candidateHash, "embedded input identities")
        var semanticPreimage = Array("ERGENTICS-GATE-E-STATIC-SEMANTIC-V1".utf8) + [0]
        semanticPreimage += (0..<8).reversed().map { UInt8(truncatingIfNeeded: UInt64(StaticPins.jsonBytes.count) >> (8 * $0)) }
        semanticPreimage += StaticPins.jsonBytes
        try require(bootstrapSHA256(semanticPreimage) == StaticPins.semanticRoot, "embedded semantic commitment")
        let arena = try DirectoryArena()
        directoryArena = arena
        sources = try StaticPins.sources.map { try HeldFile($0, arena: arena) }
        images = try StaticPins.images.map { try HeldFile($0, arena: arena) }
        control = try HeldFile(FilePin(path: StaticPins.controlPath, size: 28_799, digest: StaticPins.controlDigest,
                                      mode: 0o644, device: nil, inode: nil, image: nil), arena: arena)
        inventory = try SourceInventory(arena: arena)
        // This one serial owner configures SIGCHLD before any fixed child.
        let sigchld = gebs_configure_sigchld()
        _ = try checked(sigchld, "SIGCHLD default/no-auto-reap")
        let createdRoot = try RunRoot(arena: arena)
        root = createdRoot
        let log = Journal(root: createdRoot)
        journal = log
        let json = try RuntimeLeaf(root: createdRoot, name: "candidate-json.bin", cap: 4_194_304)
        retained[json.name] = json
        try json.writeInput(StaticPins.jsonBytes)
        let cbor = try RuntimeLeaf(root: createdRoot, name: "candidate-cbor.bin", cap: 4_194_304)
        retained[cbor.name] = cbor
        try cbor.writeInput(StaticPins.cborBytes)
        let cut = try captureBoundary()
        try log.publish("00-start.json", fields: [
            "boundary": cut.observation, "event": .text("STATIC_BOOTSTRAP_START"),
            "sigchld_configuration": rawObservation(sigchld),
            "budgets_are_not_call_observations": .flag(true),
            "maximum_fixed_child_entries": .unsigned(3), "maximum_KILL_commitments_per_owned_child": .unsigned(1),
            "source_subject_commit": .text("04c5324ccfc6984ad7c407e93238cc44f9ce22dd"),
            "source_subject_tree": .text("10615a2d66720b70ecafa891ab26e96ac9ee812e"),
            "source_subject_identity": .text("2c25246de1b50148d8193167880828815b17c80e8ee66a09dec45b1430178fc1"),
            "live_source_admission": .flag(false), "mapped_image_join": .flag(false),
            "time": rawObservation(gebs_clock_sample()),
        ])
        try runJSON()
        try runCBOR()
        try runJOIN()
        try require(sequencer.next == nil && audits.count == 3, "all static stages")
        let final = try captureBoundary()
        try log.publish("90-terminal.json", fields: [
            "boundary": final.observation, "event": .text("STATIC_BOOTSTRAP_TERMINAL"),
            "result": .text("STATIC_GRAPH_JOIN_PASS_AT_RECORDED_CUT"),
            "stages": .array(audits), "whole_invocation_also_requires_normal_exit_zero": .flag(true),
            "time": rawObservation(gebs_clock_sample()),
        ])
        try log.validate()
        _ = try captureBoundary()
    }
    func captureBoundary() throws -> BoundaryCut {
        guard let inventory, let control, let root else { throw BootstrapFailure.reject("admission owner absent") }
        try inventory.validate()
        let sourceCut = try sources.map { try $0.validate() }
        let imageCut = try images.map { try $0.validate() }
        let controlCut = try control.validate()
        try root.validate()
        try journal?.validate()
        var endpoints: [String: Capture] = [:]
        for name in retained.keys.sorted() { endpoints[name] = try retained[name]!.validate() }
        // Full metadata equality + whole-file digests actually evaluated above.
        try BoundaryChecks.requireComplete(sourceMetadata: sourceCut.count, sourceDigests: sourceCut.count,
                                           imageMetadata: imageCut.count, imageDigests: imageCut.count, endpoints: true)
        try inventory.validate()
        return BoundaryCut(source: sourceCut, images: imageCut, control: controlCut, endpoints: endpoints)
    }
    private func prepare(_ stage: Stage) throws -> (FullBoundaryAdmission, StageEndpoints, GEBSClockSample) {
        try require(sequencer.next == stage, "fixed next stage")
        guard let root, let journal else { throw BootstrapFailure.reject("runtime owner absent") }
        let endpoints = try StageEndpoints(stage: stage, root: root, retained: &retained)
        let cut = try captureBoundary()
        let clock = gebs_clock_sample()
        try require(clock.kernel_result == 0 && clock.numerator > 0 && clock.denominator > 0, "pre-spawn clock")
        try journal.publish(stage.entryLeaf, fields: [
            "boundary": cut.observation, "event": .text("FIXED_STAGE_ENTRY_INTENT"),
            "stage": .text(stage.label), "start": rawObservation(clock),
            "spawn_entered_observation": .null,
            "deadline_nanoseconds": .unsigned(5_000_000_000),
        ])
        let token = try FullBoundaryAdmission.prepare(owner: self, endpoints: endpoints, expected: cut, start: clock)
        return (token, endpoints, clock)
    }
    private func runJSON() throws {
        let (token, endpoints, start) = try prepare(.json)
        try acceptSpawn(try token.consumeJSON(), endpoints: endpoints, start: start)
    }
    private func runCBOR() throws {
        let (token, endpoints, start) = try prepare(.cbor)
        try acceptSpawn(try token.consumeCBOR(), endpoints: endpoints, start: start)
    }
    private func runJOIN() throws {
        let (token, endpoints, start) = try prepare(.join)
        try acceptSpawn(try token.consumeJOIN(), endpoints: endpoints, start: start)
    }
    private func acceptSpawn(_ spawn: GEBSSpawnResult, endpoints: StageEndpoints, start: GEBSClockSample) throws {
        // First retain the raw result, then the exact PID owner; no journal,
        // close, capture parsing, or teardown-error throw precedes ownership.
        lastSpawn = spawn
        enteredStage = endpoints.stage
        try require(spawn.spawn_entered == 1 && spawn.spawn_result == 0 && spawn.pid > 1, "fixed spawn failed")
        let child = try OwnedChild(pid: spawn.pid, start: start) // positive PID check already satisfied.
        active = child
        let teardownFailed = spawn.actions_destroy_result != 0 || spawn.attributes_destroy_result != 0
        child.finish(forceDisposal: teardownFailed)
        try require(child.state.isReaped && !child.state.ownershipLost, "exact reap/conservation missing")
        try endpoints.closeInputs()
        for target in endpoints.outputs.keys.sorted() { try endpoints.outputs[target]!.sealAfterReapOrInputWrite() }
        let cut = try captureBoundary()
        try require(child.normalSuccess && !teardownFailed, "child exit/deadline/teardown failure")
        let stage = endpoints.stage
        func bytes(_ name: String) throws -> [UInt8] {
            guard let result = retained[name]?.sealed?.bytes else { throw BootstrapFailure.reject("missing capture") }
            return result
        }
        try require(try bytes(stage.outputs[2]!).isEmpty, "nonempty stderr")
        switch stage {
        case .json:
            jsonBinding = try ReceiptBinding.projector(codec: .json, graph: bytes("12-json-graph.json"),
                verifier: bytes("11-json-verifier.json"), roundTrip: bytes("13-json-roundtrip.json"))
        case .cbor:
            cborBinding = try ReceiptBinding.projector(codec: .cbor, graph: bytes("22-cbor-graph.json"),
                verifier: bytes("21-cbor-verifier.json"), roundTrip: bytes("23-cbor-roundtrip.json"))
            try require(jsonBinding == cborBinding && bytes("12-json-graph.json") == bytes("22-cbor-graph.json"),
                        "cross-codec external graph join")
        case .join:
            guard let jsonBinding, let cborBinding else { throw BootstrapFailure.reject("missing projector joins") }
            try ReceiptBinding.join(graph: bytes("32-authoritative-static-graph.json"), jsonGraph: bytes("12-json-graph.json"),
                cborGraph: bytes("22-cbor-graph.json"), receipt: bytes("31-join-receipt.json"), json: jsonBinding, cbor: cborBinding)
        }
        guard let journal else { throw BootstrapFailure.reject("journal missing") }
        let audit: Observation = .object(["stage": .text(stage.label), "spawn": rawObservation(spawn), "child": child.observation])
        try journal.publish(stage.exitLeaf, fields: [
            "boundary": cut.observation, "event": .text("FIXED_STAGE_COMPLETE"),
            "result": .text("PASS_STATIC_STAGE"), "stage": .text(stage.label),
            "spawn": rawObservation(spawn), "child": child.observation,
        ])
        audits.append(audit)
        try sequencer.finish(stage)
    }
    func fail(_ error: Error) {
        sequencer.reject()
        // Exact ownership survives every post-spawn throw. This does not adopt
        // old processes or infer signal authority from a journal PASS.
        active?.finish(forceDisposal: true)
        guard let journal, !journal.terminalAttempted else { return }
        var fields: [String: Observation] = [
            "event": .text("STATIC_BOOTSTRAP_TERMINAL"), "result": .text("FAIL_NO_RETRY"),
            "error": .text(String(describing: error)), "completed_stages": .array(audits),
            "entered_stage": enteredStage.map { .text($0.label) } ?? .null,
            "last_spawn": lastSpawn.map { rawObservation($0) } ?? .null,
            "last_child": active.map(\.observation) ?? .null,
            "time": rawObservation(gebs_clock_sample()),
        ]
        fields["conservation"] = .text(active == nil ? "NO_SUCCESSFUL_CHILD_CAPTURED" :
            (active!.state.isReaped ? "EXACT_CHILD_REAPED_NO_GROUP_CLAIM" : "UNPROVEN"))
        // One terminal attempt. Failure retains the partial leaf/prefix and is
        // not repaired, replaced, retried, or reinterpreted as complete.
        try? journal.publish("90-terminal.json", fields: fields)
    }
}
public enum GateEStaticBootstrap {
    /// Closed coordinator only. No caller-selected inputs or runtime settings.
    /// Future entry requires a separately frozen, explicitly approved launch.
    public static func run() -> Int32 {
        let owner = Run()
        do { try owner.execute(); return 0 }
        catch { owner.fail(error); return 70 }
    }
}
